### ISSUE TITLE
Coc: Server languageserver.tmux initialization failed. _ResponseError: Pending response rejected since connection got disposed

### ISSUE THREAD

**Issue by meinzer1899** [Freed-Wu/tmux-language-server#3]
When using `tmux-language-server`, I get the following error opening .tmux.conf:

<details>
<summary>coc error log</summary>

```
## versions

vim version: VIM - Vi IMproved 9.1 9010474
node version: v20.14.0
coc.nvim version: 0.0.82-c054573 2024-06-06 15:28:44 +0300
coc.nvim directory: /home/sebastian/.vim/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2024-06-11T13:16:03.536 INFO (pid:337948) [configurations] - Add folder configuration from cwd: /home/sebastian/dotfiles/.vim/coc-settings.json
2024-06-11T13:16:03.617 INFO (pid:337948) [plugin] - coc.nvim initialized with node: v20.14.0 after 116
2024-06-11T13:16:04.663 INFO (pid:337948) [attach] - receive notification: doAutocmd [ 2, 1 ]
2024-06-11T13:16:04.718 INFO (pid:337948) [services] - LanguageClient tmux state change: stopped => starting
2024-06-11T13:16:04.725 INFO (pid:337948) [language-client-index] - Language server "languageserver.tmux" started with 338108
2024-06-11T13:16:04.842 INFO (pid:337948) [attach] - receive notification: highlight []
2024-06-11T13:16:05.042 INFO (pid:337948) [services] - LanguageClient tmux state change: starting => stopped
2024-06-11T13:16:05.042 INFO (pid:337948) [services] - LanguageClient tmux state change: stopped => starting
2024-06-11T13:16:05.042 ERROR (pid:337948) [language-client-client] - Server languageserver.tmux initialization failed. _ResponseError: Pending response rejected since connection got disposed
    at Object.dispose (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:20762:25)
    at Object.dispose (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:73464:31)
    at LanguageClient.handleConnectionClosed (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:74382:30)
    at LanguageClient.handleConnectionClosed (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:74884:15)
    at closeHandler (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:74369:16)
    at CallbackList.invoke (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:18921:35)
    at _Emitter.fire (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:18980:34)
    at closeHandler (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:19972:24)
    at CallbackList.invoke (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:18921:35)
    at _Emitter.fire (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:18980:34) {
  code: -32097,
  data: undefined
}
```

</details>

I used https://tmux-language-server.readthedocs.io/en/latest/resources/configure.html#coc-nvim for the setup.

**Comment by Freed-Wu** [comment]
The document is old, I'll update it.

**Comment by Freed-Wu** [comment]
Before updating, remove `initializationOptions` from your configuration. It has been depracted.

**Comment by meinzer1899** [comment]
Hi @Freed-Wu , thanks for the quick reply, update of the instructions and the language server 👍 

Unfortunately, I still face the issue. Do you have an idea? Which command shall be run to analyze a file?

<details>

```
## versions

vim version: VIM - Vi IMproved 9.1 9010474
node version: v20.14.0
coc.nvim version: 0.0.82-c054573 2024-06-06 15:28:44 +0300
coc.nvim directory: /home/sebastian/.vim/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2024-06-12T15:06:25.272 INFO (pid:253405) [configurations] - Add folder configuration from cwd: /home/sebastian/dotfiles/.vim/coc-settings.json
2024-06-12T15:06:25.350 INFO (pid:253405) [plugin] - coc.nvim initialized with node: v20.14.0 after 114
2024-06-12T15:06:27.918 INFO (pid:253405) [attach] - receive notification: doAutocmd [ 2, 1 ]
2024-06-12T15:06:27.973 INFO (pid:253405) [services] - LanguageClient tmux state change: stopped => starting
2024-06-12T15:06:27.989 INFO (pid:253405) [language-client-index] - Language server "languageserver.tmux" started with 253615
2024-06-12T15:06:28.097 INFO (pid:253405) [attach] - receive notification: highlight []
2024-06-12T15:06:28.348 INFO (pid:253405) [services] - LanguageClient tmux state change: starting => stopped
2024-06-12T15:06:28.348 INFO (pid:253405) [services] - LanguageClient tmux state change: stopped => starting
2024-06-12T15:06:28.349 ERROR (pid:253405) [language-client-client] - Server languageserver.tmux initialization failed. _ResponseError: Pending response rejected since connection got disposed
    at Object.dispose (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:20762:25)
    at Object.dispose (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:73464:31)
    at LanguageClient.handleConnectionClosed (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:74382:30)
    at LanguageClient.handleConnectionClosed (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:74884:15)
    at closeHandler (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:74369:16)
    at CallbackList.invoke (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:18921:35)
    at _Emitter.fire (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:18980:34)
    at closeHandler (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:19972:24)
    at CallbackList.invoke (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:18921:35)
    at _Emitter.fire (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:18980:34) {
  code: -32097,
  data: undefined
}
2024-06-12T15:06:28.350 INFO (pid:253405) [services] - LanguageClient tmux state change: starting => stopped
2024-06-12T15:06:28.350 ERROR (pid:253405) [server] - unhandledRejection  Promise {
  <rejected> _ResponseError: Pending response rejected since connection got disposed
      at Object.dispose (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:20762:25)
      at Object.dispose (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:73464:31)
      at LanguageClient.handleConnectionClosed (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:74382:30)
      at LanguageClient.handleConnectionClosed (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:74884:15)
      at closeHandler (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:74369:16)
      at CallbackList.invoke (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:18921:35)
      at _Emitter.fire (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:18980:34)
      at closeHandler (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:19972:24)
      at CallbackList.invoke (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:18921:35)
      at _Emitter.fire (/home/sebastian/.vim/plugged/coc.nvim/build/index.js:18980:34) {
    code: -32097,
    data: undefined
  }
```

</details>

**Comment by meinzer1899** [comment]
Thanks for the update. I will try out the new version when it is released and installable via `pip`.

**Comment by Freed-Wu** [comment]
latest version is for you :+1:

**Comment by meinzer1899** [comment]
I found a solution, the coc output was a false lead. It was a problem with a dependency of `lsp_tree_sitter`.

When I try to start the server manually
```zsh
> tmux-language-server                                                                                         
Traceback (most recent call last):
  File "/home/sebastian/.local/bin/tmux-language-server", line 8, in <module>                                      
sys.exit(main())
  File "/home/sebastian/.local/lib/python3.10/site-packages/tmux_language_server/__main__.py", line 111, in main                                                                                                                  from .server import TmuxLanguageServer                                                                       
  File "/home/sebastian/.local/lib/python3.10/site-packages/tmux_language_server/server.py", line 9, in <module>                                                                                                                  from lsp_tree_sitter.finders import PositionFinder                                                           
  File "/home/sebastian/.local/lib/python3.10/site-packages/lsp_tree_sitter/finders.py", line 11, in <module>      from jsonschema import Validator                                                                           
ImportError: cannot import name 'Validator' from 'jsonschema' (/usr/lib/python3/dist-packages/jsonschema/__init__.py) 
```

I had to upgrade jsonschema `pip install --upgrade jsonschema`. 
![grafik](https://github.com/Freed-Wu/tmux-language-server/assets/44314956/1b2ad34a-91d3-47eb-a685-8f192a24fade)


I had assumed that this transitive dependency gets upgraded automatically to a valid version by executing `pip install tmux-language-server`?

**Comment by Freed-Wu** [comment]
Maybe `pip install -U tmux-language-server`?

**Comment by meinzer1899** [comment]
This would update `tmux-language-server` (e.g. from 0.0.9 to 0.0.10), not the dependencies, right? Because the requirements.txt just says `lsp-tree-sitter`, and `lsp-tree-sitter` just says `jsonschema`. And I had a version of `jsonschema` installed, but an incompatible one (see above).

I think the problem is that [lsp-tree-sitter](https://github.com/neomutt/lsp-tree-sitter) this package don't specify the versions of the dependencies, leading to version mismatches like I had with `jsonschema`.

I would suggest to specify the versions of the depending packages when generating requirements.txt. [pip-tools](https://github.com/jazzband/pip-tools) is great for this task.

This issue can be closed. Thanks again @Freed-Wu

**Comment by Freed-Wu** [comment]
Yep, jsonschema has incompatible API changes from 3.X to 4.X.
